loja/urls.py
from django.urls import include, path
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

produto/urls.py
from django.urls import path
from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name="lista"),
    path('<slug>', views.DetalheProduto.as_view(), name="detalhe"),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(),
         name="adicionaraocarrinho"),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(),
         name="removerdocarrinho"),
    path('carrinho/', views.Carrinho.as_view(), name="carrinho"),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name="resumodacompra")
]

produto/models.py
from django.conf import settings
import os
from PIL import Image
from django.db import models
from django.utils.text import slugify
# Create your models here.
from utils import money


class Produto(models.Model):
    nome = models.CharField(max_length=255)
    descricao_curta = models.TextField(max_length=255)
    descricao_longa = models.TextField()
    imagem = models.ImageField(
        upload_to='produto_imagens/%Y/%m', blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    preco_marketing = models.FloatField(verbose_name='Preço')
    preco_marketing_promocional = models.FloatField(
        default=0, verbose_name='Preço Promo.')
    tipo = models.CharField(
        default='V',
        max_length=1,
        choices=(('V', 'Variável'), ('S', 'Simples'))
    )

    def get_preco_formatado(self):
        return money.formata_preco(self.preco_marketing)

    get_preco_formatado.short_description = 'Preço'

    def get_preco_promocional_formatado(self):
        return money.formata_preco(self.preco_marketing_promocional)

    get_preco_promocional_formatado.short_description = 'Preço'

    @staticmethod
    def resize_image(img, new_width=800):
        print(img.name)
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        print(img_full_path)
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size

        if original_width <= new_width:
            print('Retornando largura original menor que nova largura')
            img_pil.close()
            return

        new_height = round((new_width * original_height) / original_width)
        new_img = img_pil.resize((new_width, new_height), Image.LANCZOS)
        new_img.save(img_full_path, optimize=True, quality=50)

    def save(self, *args, **kwargs):

        if not self.slug:
            self.slug = f'{slugify(self.nome)}'

        super().save(*args, **kwargs)
        max_image_size = 800

        if self.imagem:
            self.resize_image(self.imagem, max_image_size)

    def __str__(self):
        return self.nome


class Variacao(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    nome = models.CharField(max_length=50, blank=True, null=True)
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    estoque = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.nome or self.produto.nome

    class Meta:
        verbose_name = 'Variação'
        verbose_name_plural = 'Variações'

produto/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.http import HttpResponse
from . import models
from django.contrib import messages
from django.urls import reverse
from pprint import pprint


class ListaProdutos(ListView):
    # def get(self, request, *args, **kwargs):
    #     return HttpResponse('ListaProdutos')
    model = models.Produto
    template_name = 'produto/lista.html'
    context_object_name = 'produtos'
    paginate_by = 10


class DetalheProduto(DetailView):
    # def get(self, request, *args, **kwargs):
    #     return HttpResponse('DetalheProduto')
    model = models.Produto
    template_name = 'produto/detalhe.html'
    context_object_name = 'produto'
    slug_url_kwarg = 'slug'


class AdicionarAoCarrinho(View):
    def get(self, request, *args, **kwargs):

        # if self.request.session.get('carrinho'):
        #     del self.request.session['carrinho']
        #     self.request.session.save()

        http_referer = self.request.META.get(
            'HTTP_REFERER', reverse('produto:lista'))

        variacao_id = self.request.GET.get('vid')
        if not variacao_id:
            messages.error(self.request, 'Produto não existe')
            return redirect(http_referer)

        variacao = get_object_or_404(models.Variacao, id=variacao_id)
        if variacao.estoque < 1:
            messages.error(self.request, 'Estoque insuficiente')
            return redirect(http_referer)

        # return redirect(self.request.META['HTTP_REFERER'])

        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = {}
            self.request.session.save()

        carrinho = self.request.session['carrinho']
        produto = variacao.produto

        imagem = produto.imagem.name if produto.imagem else ''

        if variacao_id in carrinho:
            quantidade_carrinho = carrinho[variacao_id]['quantidade']
            quantidade_carrinho += 1

            if variacao.estoque < quantidade_carrinho:
                messages.warning(self.request,
                                 f'Estoque insuficiente para {quantidade_carrinho}x no '
                                 f'produto "{produto.nome}". Adicionamos {variacao.estoque}x '
                                 f'no seu carrinho.')

                quantidade_carrinho = variacao.estoque

            carrinho[variacao_id]['quantidade'] = quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo'] = variacao.preco * \
                quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo_promocional'] = variacao.preco_promocional * \
                quantidade_carrinho

        else:
            carrinho[variacao_id] = {
                'produto_id': produto.id,
                'produto_nome': produto.nome,
                'variacao_nome': variacao.nome or '',
                'variacao_id': variacao.id,
                'preco_unitario': variacao.preco,
                'preco_unitario_promocional': variacao.preco_promocional,
                'preco_quantitativo': variacao.preco,
                'preco_quantitativo_promocional': variacao.preco_promocional,
                'quantidade': 1,
                'slug': produto.slug,
                'imagem': imagem
            }

        self.request.session.save()
        # pprint(carrinho)

        messages.success(self.request,
                         f"Produto {produto.nome} {variacao.nome} adicionado ao seu carrinho "
                         f"{carrinho[variacao_id]['quantidade']}x.")

        # retcrn HttpResponse(f'{variacao.produto} {variacao.nome}')

        return redirect(http_referer)


class RemoverDoCarrinho(View):
    def get(self, request, *args, **kwargs):

        http_referer = self.request.META.get(
            'HTTP_REFERER', reverse('produto:lista'))

        variacao_id = self.request.GET.get('vid')
        carrinho = self.request.session.get('carrinho')
        if not variacao_id \
                or not carrinho \
                or variacao_id not in carrinho:
            return redirect(http_referer)

        produto_removido = carrinho[variacao_id]
        messages.success(self.request,
                         f'Produto {produto_removido["produto_nome"]} {produto_removido["variacao_nome"]}'
                         f'removido do seu carrinho.'
                         )
        # return HttpResponse('RemoverDoCarrinho')

        del self.request.session['carrinho'][variacao_id]
        self.request.session.save()
        return redirect(http_referer)


class Carrinho(View):
    def get(self, request, *args, **kwargs):
        """
        Poderia pegar logo no template o "request.session.carrinho"
        """

        contexto = {
            'carrinho': self.request.session.get('carrinho', {})
        }

        # return HttpResponse('Carrinho')
        return render(self.request, 'produto/carrinho.html', contexto)


class ResumoDaCompra(View):
    def get(self, request, *args, **kwargs):
        return HttpResponse('ResumoDaCompra')

produto/templates/produto/carrinho.html
{% extends 'base.html' %}
{% load omfilters %}
{% load static %}
{% block conteudo %}

{% comment %} {{request.session.carrinho}} {% endcomment %}
{% comment %} {% if request.session.carrinho %} {% endcomment %}
{% if carrinho %}
<div class="row mt-3">
    <div class="col">
        <h3>Carrinho de compras</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

        <div class="table-responsive">
            <table class="table">
                <tr>
                    <th class="d-none d-lg-block">Imagem</th>
                    <th>Produto</th>
                    <th>V.</th>
                    <th>QTD.</th>
                    <th>Total</th>
                </tr>


                {% comment %} {% for key, linha in request.session.carrinho.items %}  {% endcomment %}
                {% for linha in carrinho.values %}
                {{linha}}
                <tr>
                    <td class="d-none d-lg-block">
                        <img class="cart-img" src="{% get_media_prefix %}{{linha.imagem}}">
                    </td>
                    <td>
                        <a href="{% url 'produto:detalhe' linha.slug %}">
                        {{linha.produto_nome}}
                        </a>
                        <a class="ml-3" href="{% url 'produto:removerdocarrinho' %}?vid={{linha.variacao_id}}">
                            <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                        </a>
                    </td>
                    <td>{{linha.variacao_nome}}</td>
                    <td>{{linha.quantidade}}x
                        {% if linha.preco_unitario_promocional %}
                        {{linha.preco_unitario_promocional |formata_preco}}
                        {% else %}
                        {{linha.preco_unitario |formata_preco}}
                        {% endif %}
                    </td>
                    
                    {% if linha.preco_quantitativo_promocional %}
                    <td>{{linha.preco_quantitativo_promocional |formata_preco}}</td>
                    {% else %}
                    <td>{{linha.preco_quantitativo |formata_preco}}</td>
                    {% endif %}
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>
</div>



<div class="row mt-3">
    <div class="col-lg">
        <p class='lead'>Total no carrinho</p>

        <div class='table-responsive'>
            <table class="table">
                <tr>
                    <td class="font-weight-bold">Total</td>
                    <td>{{ carrinho | cart_totals | formata_preco }}</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="col-lg mt-auto">
        <a class="btn btn-lg btn-block btn-primary" href="#">
            Finalizar a compra
        </a>
    </div>
</div>


{% else %}
<div class="row mt-3">
    <div class="col">
        <h3>Carrinho vazio</h3>
        <p class="lead">Não há produtos no seu carrinho.</p>
    </div>
</div>
{% endif %}

{% endblock %}

produto/templates/produto/detalhe.html
{% extends 'base.html' %}
{% load omfilters %}

{% block conteudo %}
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg">
                <div class="row no-gutters">
                    <div class="col-lg-12">
                        <img class="img-fluid" src="{{produto.imagem.url}}">
                    </div>
                </div>
            </div>
            <div class="col-lg">
                <div class="mt-4 mt-lg-0">
                    <h1 class="h2">{{produto.nome }}</h1>
                    <p class="lead">{{produto.descricao_curta }}</p>
                    <p class="lead">
                        {% if produto.preco_marketing_promocional %}
                        <span id="variation-preco-promocional" class="lead product-price"> {{produto.get_preco_promocional_formatado}}</span>
                        <span id="variation-preco"
                            class="lead product-old-price text-muted">{{produto.get_preco_formatado}}</span>
                            {% else %}
                            <span id="variation-preco-promocional"
                            class="lead product-old-price text-muted">{{produto.get_preco_formatado}}</span>
                            {% endif %}
                    </p>

                    <form action="/adicionaraocarrinho/" id="form-add-to-cart">
                        <div class="form-group">
                            <select id="select-variacoes" name="vid" class="form-control form-control-lg">
                                {% for variacao in produto.variacao_set.all %}

                                {% if variacao.preco_promocional %}

                                <option data-preco="{{variacao.preco|formata_preco}}" data-preco-promocional="{{variacao.preco_promocional|formata_preco}}" value="{{variacao.id}}">
                                    {% if variacao.nome %}
                                    {{variacao.nome}}
                                    {% else %}
                                    {{variacao}}
                                    {% endif %}
                                </option>
                                {% else %}
                                <option data-preco="{{variacao.preco|formata_preco}}"  value="{{variacao.id}}">            {% if variacao.nome %}
                                    {{variacao.nome}}
                                    {% else %}
                                    {{variacao}}
                                    {% endif %}
                                </option>
                                {% endif %}
                                {% endfor %}
                           
                            </select>
                        </div>

                        <div class="text-left">
                            <button type="submit" class="btn btn-primary btn-lg btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Adicionar ao carrinho
                            </button>
                        </div>

                    </form>


                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="mt-5 mb-5">
                    <h2 class="text-center">{{produto.nome}}</h2>
                   {{produto.descricao_longa}}
                </div>
            </div>
        </div>
{% endblock %}

produto/templates/produto/lista.html
{% extends 'base.html' %}
{% load omfilters %}
{% block conteudo %}
 <div class="row">
            <div class="col-lg-12">
                <div class="card-columns">


                    {% for produto in produtos %}
                    <div class="card">
                        {% if produto.imagem %}
                        <a href={{produto.slug}}>
                        <img class="card-img-top" src="{{produto.imagem.url}}" alt="Card image cap">
                        </a>
                        
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{produto.nome}}</h5>
                            <p class="card-text">{{produto.descricao_curta}}</p>
                            <div class="container product-price-block text-center">

                            {% if produto.preco_marketing_promocional %}
                                <span class="product-price">
                                    {{produto.get_preco_promocional_formatado}}
                                </span>
                                <span class="product-old-price text-muted">
                                      {{produto.get_preco_formatado}}
                                </span>
                            {% else %}
                                <span class="product-price">
                                    {{produto.preco_marketing |formata_preco}}
                                </span>
                            {% endif %}
                                
                            </div>
                        </div>
                        <div class="card-footer bg-transparent border-top-light-custom text-center">
                            <a href="{{produto.slug}}" class="btn btn-primary btn-sm m-1 btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Comprar
                            </a>
                        </div>
                    </div>
                    {% endfor %}




                </div>
            </div>
        </div>

<div class="row">
    <div class="col">
        {% include 'parciais/_pagination.html' %}
    </div>
</div>

{% endblock %}